[package]
name = "riscv-vm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "riscv-vm"
path = "src/main.rs"

[dependencies]
riscv-core = { path = "../riscv-core" }
riscv-supervisor = { path = "../riscv-supervisor" }
riscv-devices = { path = "../riscv-devices", features = ["std"] }
riscv-hostnet = { path = "../riscv-hostnet" }
riscv-machine = { path = "../riscv-machine", features = ["std"] }
